project:
  type: book

book:
  title: "qmd"
  author: "Norah Jones"
  date: "2025/6/1"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/summary.qmd
    - references.qmd

bibliography: "../main.bib"

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt
  epub:
    cover-image: cover.png
