# 素数判定

`素数判定`\index{素数判定}(Primality Test)是一个数论中十分基本,却又趣味盎然的问题.
判定一个整数是否是素数,最为朴素的想法是直接利用素数的定义,用小的素数去一一试除,如果能整除的话,那就能确定无疑为合数了.
根据Mertens定理（参见[@yao07]），可以估算出大约有76%的奇数有小于100的素因子,可见这种最平凡的方法有时十分有效.
在本章中，我们将用$N$来表示待判定的目标数.

相比整数的因子分解，素数判定一直以来被认为是较为容易的问题。
2002年三位印度计算机科学家Agrawal，Kayal，Saxena[@aks04]找到了素数判定的多项式算法
（被称为`AKS算法`\index{AKS算法}），其时间复杂度为$O(\ln^{12} N)$。
AKS算法在理论上有重要的意义，不过实践中还要更多地考虑效率问题。
实践中的素数检测方法大致分为两类，一类是确定性的，
例如Lehmer $N-1$检测，Lucas $N+1$检测，`椭圆曲线素性证明`\index{椭圆曲线素性证明}(`ECPP`\index{ECPP})等等，
当输出结果为"素数"时，能够保证被检测数一定为素数；
另一类是概率性的，如Rabin-Miller检测，Baillie-PSW检测等等，当输出结果为"素数"时，仅以一定的高概率保证被检测数的素性。
不过概率性检测一般要比确定性检测快得多。

`APRCL方法`\index{APRCL方法}将Fermat类型的想法运用到分圆域中,最先由Adleman,Pomerance,Rumely[@apr]提出,
后经Cohen,Lenstra[@cl]的改进，时间复杂度为"近似"多项式的$O((\ln N)^{c\ln\ln\ln N})$，其中$c$为一个常数。
椭圆曲线素数证明最早由Goldwasser,Kilian[@gk86]提出，后经Atikin，Morain[@atk93]改进和实现，平均时间复杂度达到了$O(\ln^6 N)$。
这两种方法已经成为目前实践上最快的确定性检测方法，并在密码学等领域有重要的应用。
鉴于我们的目的，不能用太多篇幅来介绍这两种方法，详细可参阅文献[@cohen].

有些素数判定方法严格来说应当是`合性检测`\index{合性检测}(Compositeness Test),
这类方法总可以有效地把素数判定出来,而有可能把一个合数判定为素数.
也就是说,此类方法判定一个数为合数总是准确无误的,
而"漏网的",即无法判定的合数往往称为`伪素数`\index{伪素数}(Pseudoprimes).

阅读本章需要读者初等数论和抽象代数的基础知识（例如[@fkq03],[@nlzdss00]）。
本章的主要参考书是[@riesel]，[@cohen]和[@pei02].
读者也可以参考写的十分通俗易懂的[@yan08]及其他算法/计算数论方面的相关文献。


## Fermat检测

几乎所有素数检测的想法之基石均为著名的`Fermat小定理`\index{Fermat小定理}，即若$p$为素数，$(a,p)=1$，则

$$
a^{p-1}\equiv1\pmod{p}.
$$

由此我们得到最简单的检测算法——`Fermat合性检测`\index{Fermat 检测}。

::: {#def-al:fermat .definition}
## 算法：Fermat 小定理作为合性检测
任取整数$a$，如果$(a,N)=1$且$a^{N-1}\not\equiv1\pmod{N}$，则输出$N$为合数，否则输出$N$可能为素数。
:::

::: {#def-pseudo:fermat .definition}
## Fermat 伪素数
满足 $a^{N-1}\equiv1\pmod{N}$ 的合数 $N$ 称为一个(对于基$a$)的 `Fermat伪素数`\index{伪素数}\index{Fermat 伪素数}。
:::

在$25\times10^9$以下，有21853个对于基$a=2$的Fermat伪素数（参考[@psw]），
如果对其再进行基为$a=3$的检测的话，伪素数将还剩下4709个，对于$a=2,3,5$有2552个，$a=2,3,5,7$有1770个。

运用Fermat检测的关键是如何快速计算$a^{d} \mod N$。
求幂运算采取二进算法 @def-al:r2l ，@def-al:l2r ，可以使Fermat检测的算法复杂度降到平均$1.5\log N\cdot M(N)$
（其中$M(N)$表示乘法运算的复杂度），已经为多项式阶的算法了。
使用Montgomery约化算法@def-al:monredc 可以更进一步地提高速度。

`Camichael数`\index{伪素数}\index{Camichael 数}是看起来比Fermat伪素数条件更"苛刻"的一类数。

::: {#def-CamichaelNumber .definition}
## Camichael 数
如果合数$N$，对任意满足$(a,N)=1$的整数$a$都有$a^{N-1}\equiv1\pmod{N}$，则称$N$为Camichael数。
:::

也就是说，Camichael数都将会是Fermat检测的"漏网之鱼"。最小的Camichael数的例子是$561=3\cdot 11\cdot 17$。
在$25\times10^9$以下一共有2163个Camichael数，它比对基$a=2,3,5,7$的Fermat伪素数还要来得多的原因是，
如果恰巧$N$有2,3,5,7的因子，$N$便可以是Camichael数而非Fermat伪素数。
        

## Euler 检测

`Euler检测`\index{Euler 检测}基于Euler的二次剩余定理，即若$p$为奇素数，$(a,p)=1$，
则
$$
a^{(p-1)/2}\equiv\legendre{a}{p}\pmod{p}.
$$

其中$\legendre{a}{p}$是`Legendre符号`\index{Legendre 符号}。

::: {#def-al:EulerTest  .definition}
## 算法：Euler判则作为合性检测

设$N$为奇数，任取整数$a$，满足$(a,N)=1$：

1. 如果 $a^{(N-1)/2}\not\equiv\pm1\pmod{N}$，则输出$N$为合数。
2. 如果 $a^{(N-1)/2}\equiv\pm1\pmod{N}$ 且 $a^{(N-1)/2}\not\equiv\legendre{a}{N}\pmod{N}$，则输出$N$为合数。
3. 如果 $a^{(N-1)/2}\equiv\legendre{a}{N}\pmod{N}$，则输出$N$可能为素数。
:::

::: {#def-pseudo:euler  .definition}
## Euler伪素数
如果合数$N$，$(a,N)=1$，满足$a^{(N-1)/2}\equiv\legendre{a}{N}\pmod{N}$，
则称$N$为(对于基$a$的)`Euler伪素数`\index{伪素数}\index{Euler 伪素数}。
:::

::: {#def-pseudo:strong  .definition}
## 强伪素数
设$N$奇合数，$N-1=d\cdot 2^s$，$d$为奇数。
$N$被称为(对于基$a$的)`强伪素数`\index{伪素数}\index{强伪素数}，
如果
$$
a^d\equiv 1 \pmod{N}
$$
或者对于某一个$r(0\le r\le s-1)$有
$$
a^{d\cdot 2^r}\equiv -1 \pmod{N}.
$$
:::

::: {#rem-strong  .remark}
强伪素数的定义可以这样看出：若$N$为素数，
则
\begin{align*}
  a^{N-1}-1&=(a^d-1)(a^d+1)(a^{2d}+1)(a^{4d}+1)\cdots(a^{2^{s-1}d}+1)\\
     &\equiv 0\pmod{N}.
\end{align*}
:::

对于Euler伪素数和强伪素数均不会出现类似Fermat伪素数的情况，
也就是说，只要测试的基$a$足够多，最终总可以将合数和素数分辩开来。
$25\times10^9$以下只有13个同时为对基2,3,5的强伪素数。

::: {.remark}
[@psw]证明了，Euler伪素数必定是强伪素数。
:::


## Lehmer $N-1$ 型检测

`Lehmer $N-1$型检测`\index{Lehmer $N-1$型检测}有时候$N$的素性很难判定，而$N\pm1$的分解却很容易得到。
这一节的方法便是依赖于$N-1$的素因子分解。

`Lehmer的逆定理`\index{Fermat 小定理}\index{Lehmer 的逆定理}

::: {#thm-FermatConverse .theorem}
## Fermat小定理逆定理, Lehmer
设有素因子分解$N-1=q_1^{\beta_1}\cdots q_n^{\beta_n}$。
如果对$a$有
$$
a^{(N-1)/q_j}\not\equiv1 \pmod{N},\qquad \forall j=1,2,\ldots,n,
$$
且
\begin{equation}
a^{N-1}\equiv1 \pmod{N} .
\end{equation}
{#eq-fermat}
则$N$为素数。
:::

::: {.proof}
从简化剩余系的乘法群 $M_N=(\mathbb{Z}/N\mathbb{Z})^*$ 角度来看，条件保证了$a$为$M_N$的一个$N-1$阶元素，
而 $|M_N|=\varphi(N)$ ($\varphi$ 为Euler函数)，从而有$\varphi(N)\ge N-1$，这就保证了$N$为素数。
:::

::: {.remark}
这里不要$(a,N)=1$的条件，是因为其已经被包括在式 @eq-fermat 之中了。
:::

寻找$M_N$的生成元(甚至只寻找模$N$的一个二次剩余)都是非常困难的事情，目前还没有有效的确定性的方法。
一个现实的问题是如果$N$为伪素数，如何才能快速的找到Lehmer $N-1$检测中符合条件的$a$，即$M_N$的一个生成元呢？有一些步骤可以采用：

1. 排除所有$\legendre{a}{N}=1$的$a$，这就排除了一半可能的$a$！
2. 从较小的$q_j$开始检测，因为$q_j$越小，失败的可能性越大。

`Selfridge的多基推广`\index{Fermat 小定理}\index{Lehmer 的逆定理!Selfridge 的多基推广}

::: {#thm-multibase-n-1 .theorem}
## Selfridge的多基推广
如果$\forall q_j$，$\exists a_j$使得
$$
a_j^{(N-1)/{q_j}}\not\equiv1 \pmod{N}
$$
且
$$
a_j^{N-1}\equiv1 \pmod{N} .
$$
则$N$为素数。
:::

::: {.proof}
设$a_j$模$N$的阶为$r_j$，则以上两式表明 $r_j\nmid\frac{N-1}{q_j}$ 且 $r_j\mid N-1$，
从而$q_j^{\beta_j}\mid r_j\Rightarrow N-1\mid \varphi(N) \Rightarrow \varphi(N)=N-1$。
:::

::: {.remark}
这个方法对$M_N$的生成元很大的时候非常有用，因为我们不必找出一个"共同"的$a$来。
:::

`Pepin定理`\index{Pepin定理}

::: {#thm-pepin .theorem}
## Pepin定理
设$F_n=2^{2^{n}}+1$为Fermat素数($n\ge1$)。
则$F_n$为素数当且仅当
$$
3^{2^{2^{n-1}}}\equiv-1 \pmod{F_n}
$$
:::

::: {.proof}
用定理 @thm-FermatConverse 即可，只需注意到3必为$12n\pm 5$型素数的二次非剩余。
:::

::: {.remark}
使用这个方法，在1963年[@sel64]证明了$F_{14}$(有4933个十进制位)是合数，尽管但现在为止还不知道其任何一个因子。
:::

下面的定理让我们可以拥有不必完全分解$N-1$的便利。

`放宽版本`\index{Fermat小定理}\index{Lehmer的逆定理!放宽版本}

::: {#thm-RelaxedFermatConverse .theorem}
## Lehmer定理的放宽版本
设$N-1=RF$，$(R,F)=1$且$R<F$，有素因子分解$F=\prod\limits_{j=1}^n q_j^{\beta_j}$。
若有$a$使得
$$
a^{(N-1)/q_j}\not\equiv1 \pmod{N},\qquad \forall j=1,2,\ldots,n
$$
且
$$
a^{N-1}\equiv1 \pmod{N},
$$
则$N$为素数。
:::

::: {.proof}
设$p$为素数，$p\mid N$，设$a$模$p$的阶是$d$，则由条件有$d\mid N-1$，但 $d\nmid \frac{N-1}{q_j}$。
从而$\forall j$，$d\mid \prod\limits_{i=1}^n q_i$，但$d\nmid R\cdot q_j^{\beta_j-1}\prod\limits_{i\ne j}q_i^{\beta_i}$。
故有
$$
q_j^{\beta_j}\mid d\Rightarrow F\mid d\Rightarrow F\mid p-1 \Rightarrow F\le \sqrt{N}.
$$
矛盾！
:::

`Proth定理`\index{Proth定理}

::: {#thm-proth .theorem}
## Proth定理
设$N=h\cdot2^n+1$，其中$h$为奇数，$2^n>h$。如果存在$a$使得
$$
a^{(N-1)/2}\equiv-1 \pmod{N} .
$$
则$N$为素数。
:::

::: {.proof}
在定理@thm-RelaxedFermatConverse 中令$F=2^n$即得。
:::


## Lucas 伪素数检测与 $N+1$ 型检测

如果$N-1$也是很难分解的，这里的方法就将分解的困难转移到$N+1$上去。
想法是与$N-1$型检测是类似的，不过要将Fermat小定理从 $\mathbb{Z}$ 上推广到二次域的代数整数环上去，
替代那里的$a^{N-1}-1$的则是所谓Lucas序列$U_{N+1}$。

设$D$为无平方整数，记$O$为二次域$\mathbb{Q}(\sqrt{D})$的代数整数环，我们熟知(参见[@nlzdss00]，P139)
当$D\equiv2,3\pmod{4}$时，
$$
O=\{m+n\sqrt{D}\mid m,n\in\mathbb{Z}\},
$$

而当$D\equiv1\pmod{4}$时，
$$
O=\Big\{\frac{m+n\sqrt{D}}{2}\,\Big\vert\, m,n\in\mathbb{Z},m\equiv n\pmod{2}\Big\}.
$$

在$O$中可以很容易地讨论同余的概念，称$a\equiv b\pmod{M}$，若$a-b$属于$M$在$O$中生成的理想。
记$\bar a$为$a$在$O$中的共轭，即$\overline{r+s\sqrt{D}}=r-s\sqrt{D}$，则在$O$中我们有如下Fermat小定理的类比。

`二次域中的`\index{Fermat小定理}\index{二次域中的}

::: {#thm-quafermat .theorem}
## 二次域中的Fermat小定理
设$a\in O$，$p$为奇素数，$p\nmid D$，
则有
\begin{equation*}
  a^p\equiv
  \begin{cases}
    a&\text{若}\displaystyle\legendre{D}{p}=1\\\noalign{\smallskip}
    \bar{a}&\text{若}\displaystyle\legendre{D}{p}=-1
  \end{cases}
  \pmod{p}.
\end{equation*}
:::

::: {.proof}
设$2a=r+s\sqrt{D}$，$r,s\in\mathbb{Z}$，
则由$\mathbb{Z}$上的Fermat小定理，二项展开及Euler二次剩余定理得
\begin{align*}
  2a^p&\equiv(2a)^p\equiv(r+s\sqrt{D})^p\equiv r^p+(s\sqrt{D})^p \\
  &\equiv r+sD^{\frac{p-1}{2}}\sqrt{D} \\
  &\equiv r+s\legendre{D}{p}\sqrt{D}\pmod{p}.
\end{align*}
从而得到所要结论。
:::

定理 @thm-quafermat 中的乘幂不容易计算，为了有效地利用定理 @thm-quafermat 的结论，
我们引入`Lucas序列`\index{Lucas序列}的概念，Lucas序列实际上是一类简单的二阶递推序列。

::: {#def-de:LucasSeq .definition}
## Lucas序列
设$P ,Q\in\mathbb{Z}$，特征方程$\lambda^2-P\lambda+Q=0$的两根为$a$，$b$。
则$P $，$Q$对应的Lucas序列定义为
$$
U_n=\frac{a^n-b^n}{a-b},\qquad V_n=a^n+b^n.
$$
:::

::: {.remark}
由特征方程对应的递推关系，知道$\{U_n\},\{V_n\}$均为$\mathbb{Z}$中的序列。
:::

::: {#lem-lucas .lemma}
记号同定义 @def-de:LucasSeq ，设整数$M$满足$(QD,M)=1$，则$a,b,a-b$均模$M$可逆。
并且$U_k\equiv0\pmod{M}$当且仅当$(ab^{-1})^k\equiv1\pmod{M}$。
:::

::: {.proof}
由 $(Q,M)=1$ 知 $Q$ 模 $M$ 可逆，而 $ab=Q$，知 $ab\cdot Q^{-1}\equiv1\pmod{M}$，
从而 $a,b$ 均模 $M$ 可逆。又 $a-b=\sqrt{D}$，而 $D^{\varphi(M)}\equiv1\pmod{M}$，
可知 $(a-b)^{2\varphi(N)}\equiv1\pmod{M}$，从而 $a-b$ 也模 $M$ 可逆。

由于 $a-b$ 模 $M$ 可逆，$U_k\equiv(a-b)^{-1}(a^k-b^k)\pmod{M}$，
从而 $$U_k\equiv0\pmod{M}\Longleftrightarrow a^k\equiv b^k\pmod{M}\Longleftrightarrow (ab^{-1})^k\equiv1\pmod{M}.$$
引理得证。
:::

::: {#thm-lucasfermat .theorem}
设 $p$ 为素数，满足 $(2QD,p)=1$，
记 $\varepsilon=\legendre{D}{p}$，
则有 $U_{p-\varepsilon}\equiv0\pmod{p}$。
:::

::: {.proof}
若 $\legendre{D}{p}=1$，则由定理 @thm-quafermat 可知 $a^{p-1}\equiv b^{p-1}\equiv1\pmod{p}$，
从而 $(ab^{-1})^{p-1}\equiv1\pmod{p}$，由引理 @lem-lucas 知 $U_{p-1}\equiv0\pmod{p}$。

若 $\legendre{D}{p}=-1$，则由定理 @thm-quafermat 可知 $a^{p+1}\equiv a\bar a\equiv ab\pmod{p}$，
同理 $b^{p+1}\equiv ba\pmod{p}$，从而 $(ab^{-1})^{p+1}\equiv1\pmod{p}$，
由引理 @lem-lucas 知 $U_{p+1}\equiv0\pmod{p}$，这就完成了证明。
:::

由上面的定理我们自然地得到 `Lucas伪素数`\index{伪素数}\index{Lucas 伪素数} 的概念。

::: {#def-Lucas伪素数 .definition}
## Lucas 伪素数

设 $N$ 为奇合数，若存在 Lucas 序列 $\{U_n\}$ 
使得 $\varepsilon=\legendre{D}{N}\ne0$ 
且 $U_{N-\varepsilon}\equiv0\pmod{N}$，
则称 $N$ 为 Lucas 伪素数。
:::

正如我们在 Fermat 检测和 Euler 检测中看到的，一个伪素数概念对应着一个合性检测算法，
由此我们立即可以得到 `Lucas伪素数检测`\index{Lucas伪素数检测} 算法。

::: {#def-al:lpsp .definition}
## 算法：Lucas伪素数检测

选取 Lucas 序列参数 $P,Q$，使得 $\varepsilon=\legendre{D}{N}\ne0$。
若 $U_{N-\varepsilon}\not\equiv0\pmod{N}$ 则输出 $N$ 为合数，否则输出 $N$ 可能为素数。
:::

::: {.remark}
由于来源的不同，我们可以期望一个数同时为 Lucas 伪素数和 Fermat 伪素数（或强伪素数）的可能情形不大，
这样的观察也被用于 Baillie-PSW 检测算法 @def-al:psw 中。
:::

我们已经得到了 Lucas 伪素数合性检测，和 $N-1$ 型检测类似，我们还能够进行素性的确证。
在这里，替代 $N-1$ 的分解的是 $N+1$ 的分解，我们可以看到下面的定理与定理 @thm-FermatConverse 是多么的"形似"。
`Lucas $N+1$ 型检测`\index{Lucas $N+1$ 型检测}

::: {#thm-lucas .theorem}
## Lucas检测
设有素因子分解 $N+1=\prod\limits_{j=1}^nq_j^{\beta_j}$，
若有 Lucas 序列 $\{U_n\}$，使 $(2QD,N)=1$，
满足 $$(U_{(N+1)/q_j},N)=1,\qquad \forall j=1,2,\ldots,n$$ 
且 $$U_{N+1}\equiv0\pmod{N},$$ 则 $N$ 为素数。
:::

::: {.proof}
设 $p$ 为 $N$ 的一个素因子，设 $k$ 为最小的正整数使得 $(ab^{-1})^k\equiv1\pmod{p}$。
由条件知 $U_{N+1}\equiv0\pmod{p}$，$U_{(N+1)/q_j}\not\equiv0\pmod{p}$，
从而根据引理 @lem-lucas 知 $k\mid N+1$，$k\nmid (N+1)/q_j,\ \forall j$，
从而 $k=N+1$。但根据 $k$ 的最小性，由定理 @thm-lucasfermat 必有 $k\mid q+1$ 或 $k\mid q-1$。
从而 $q=N$，$N$ 为素数。
:::

与 $N-1$ 型检测完全类似还可以得到以下结果。

::: {#thm-RelaxedLucas .theorem}
## Lucas检测的放宽版本
设 $N+1=RF$，$(R,F)=1$ 且 $R<F$，有素因子分解 $F=\prod\limits_{j=1}^n q_j^{\beta_j}$。
若有 $\{U_k\}$ 为 Lucas 序列，$(2QD,N)=1$，
满足 $$(U_{(N+1)/q_j},N)=1,\qquad \forall j=1,\ldots,n$$ 
且 $$U_{N+1}\equiv0\pmod{N}.$$ 则 $N$ 为素数。
:::

::: {.remark}
Lucas 检测的一个优势在于 Lucas 序列可以通过递推快速地计算。
设
\begin{equation*}
A_k=
\begin{bmatrix}
  U_{k+1}&V_{k+1}\\
  U_k & V_k
\end{bmatrix},
\end{equation*}

则有
\begin{equation*}
A_k=
  \begin{bmatrix}
    P & -Q\\
    1 & 0\\
  \end{bmatrix}A_{k-1}=\cdots=
  \begin{bmatrix}
    P & -Q\\
    1 & 0\\
  \end{bmatrix}^kA_0.
\end{equation*}
可以使用快速求幂的方法在 $O(\log k)$ 步中完成序列的计算。
:::

::: {.remark}
上述基于 $N+1$ 分解的算法对 `Mersenne素数`\index{Mersenne素数} $2^n-1$ 尤其简单，
因此也被著名的 [GIMPS](http://www.mersenne.org/) (Great Internet Mersenne Prime Search) 所采用。
目前为止已知的最大的 Mersenne 素数是 GIMPS 计划在 2008 年 8 月 23 日找到的第 45 个 Mersenne 素数，共有 12978189 个十进制位。
有趣的是，2009 年 4 月 12 日找到的第 47 个 Mersenne 素数要比第 45 个来的小。
:::

`Lucas-Lehmer检测`\index{Mersenne素数}\index{Lucas-Lehmer检测}

::: {#thm-LucasMersenne .theorem}
## 对 Mersenne 素数的 Lucas-Lehmer 检测
设 $n$ 为奇数，$v_0=4$，$v_k=v_{k-1}^2-2$。
则 $M_n=2^n-1$ 为素数当且仅当 $$v_{n-2}\equiv0\pmod{M_n}.$$
:::

::: {.proof}
证明主要部分来源于定理 @thm-lucas ，然而仍有一些技术上的区别，这里就不赘述了。
完整的可见 Lehmer 在 1930 的证明 [@lehmer1930]。
另外 J.W.Bruce 在 1993 年给出了一个短至 2 页的 "trival" 版证明 [@bruce]。
:::



## 概率性的检测方法

更加富有趣味的是素性的 `概率性检测方法`\index{概率性检测方法}。
Knuth [@taocp2] 这样评价概率性的算法："与其说算法重复地猜测错，倒不如说由于硬件的失灵或宇宙射线的原因，我们的计算机在它的计算中丢了一位。"
概率性的算法使我们对传统的可靠性产生疑问：我们是否真的需要"素性"的严格确证？
概率性算法最早由 Solovay，Strassen [@solovay] 于 1974 年提出，Rabin-Miller 的改进方法为 Mathematica 软件所采用。
Baillie-PSW 检测则综合了各种概率性检测方法，目前为止仍没有找到失败的反例，并且已经验证检测对于 $10^{15}$ 以下的整数均是正确的。

### Solovay-Strassen检测
`Solovay-Strassen检测`\index{Solovay-Strassen 检测}

::: {#def-al:solovay .definition}
## 算法：Solovay-Strassen检测
1. 随机生成满足 $1\le a\le N$ 的整数 $a$；
2. 若 $(a,N)=1$ 且 $\jacobi{a}{N}\equiv a^{(N-1)/2}\pmod{N}$，
则输出 $N$ 为素数，否则输出 $N$ 可能为合数。
:::

::: {#thm-solovay .theorem}
算法 @def-al:solovay 重复执行 $k$ 次，给出错误的概率为 0
（当 $N$ 为素数时）或 $2^{-k}$（当 $N$ 为合数时）
:::

::: {.proof}
只需证明当 $N$ 为合数，$(a,N)=1$ 时，$\jacobi{a}{N}\equiv a^{(N-1)/2}\pmod{N}$ 的概率不超过 $\frac{1}{2}$ 即可。
设 
$$G=\left\{a+N\mathbb{Z}\bigm|a\in\mathbb{Z},(a,N)=1,a^{(N-1)/2}\equiv\jacobi{a}{N}\pmod{N}\right\}.$$ 
则 $G<M_N$，因此只需证明 $G\ne M_N$ 即可。

如果 $N$ 能分解为两个互素的非平凡因子 $r$，$s$，我们证明必有 $\forall a$ 满足 $(a,N)=1$ 都有 $a^{(N-1)/2}\equiv1\equiv\jacobi{a}{N}\pmod{N}$
（由 Jacobi 符号的性质便知这是不可能的）。
若不然，由中国剩余定理找到 $b$ 满足 $b\equiv1\pmod{r}$ 且 $b\equiv a\pmod{s}$。
则有 $b^{(N-1)/2}\equiv 1\pmod{r}$ 且 $b^{(N-1)/2}\equiv -1\pmod{s}$，
而这与 $b^{(N-1)/2}\equiv\pm1\pmod{N}$ 是矛盾的！

如果 $N=p^e$ 为素数幂，则 $\forall a$ 满足 $(a,N)=1$ 都有 $a^{p^e-1}\equiv1\pmod{p^e}$，
再由 Euler 定理知道 $p^{e-1}(p-1)\mid p^e-1$。
而这也是不可能的。
:::

### Rabin-Miller检测

Solovay-Strassen 检测利用了 Euler 伪素数"并不多"的性质，使用随机给出的基 $a$ 多次重复进而给出高成功率的素性检测结果。
同样的想法也可以施用于强伪素数与 Lucas 伪素数，前者便是著名的 Rabin-Miller 检测，后者则被运用到 Baillie-PSW 检测中。

`Rabin-Miller检测`\index{Rabin-Miller检测} 可以看成我们在注 @rem-strong 中的想法的一个具体化。

::: {#def-al:rabin .definition}
## 算法：Rabin-Miller 强伪素数检测
设 $N-1=d\cdot 2^s$，
1. 随机生成满足 $1\le a\le N$ 的整数 $a$；
2. 顺次计算 $$a^d,a^{2d},a^{4d},\ldots,a^{2^s\cdot d}.$$ 若计算到第 $k$ 步时有
   1. $k=1$ 且 $a^d\equiv1\pmod{N}$，输出 $N$ 可能为素数；
   2. $k>1$ 且 $a^{2^{k-1}\cdot d}\equiv-1\pmod{N}$，输出 $N$ 可能为素数；
   3. $k>s$，输出 $N$ 为合数。
:::

::: {.remark}
Rabin [@rabin] 证明了算法 @def-al:rabin 重复 $k$ 遍，给出正确判断的概率大于 $1-4^{-k}$。
:::

::: {.remark}
使用单个基 $a$ 的 Rabin-Miller 检测可能会遗漏许多基 $a$ 下的强伪素数，
因此实践中的确需要使用多基的 Rabin-Miller 测试。
例如使用前 7 个素数组成的多基 Rabin-Miller 测试，
可以保证算法在 $341550071728321\approx3.4\times10^{14}$ 以下均是有效的，
而且这个数在用前 8 个素数为基的 Rabin-Miller 测试下没有改进。
:::

### Baillie-PSW检测

只是使用多基的 Rabin-Miller 测试可能得不到好的效率。
Baillie [@bai80] 将基为 2 的 Rabin-Miller 检测与 Lucas 伪素数检测结合起来，得到更为有效的素数检测方法。
Pomerance, Selfridge, Wagstaff 在 [@psw] 中对小于 $25\times10^9$ 的数验证了算法的正确性。
尽管 Pomerance [@pom84] 指出对于充分大的 $N$，必定有 Baillie-PSW 检测的反例，并且以 30 美元悬赏找出一个算法失败的反例（后来增加到 620 美元），
不过反例至今没有找到，并且有经验估计认为第一个反例如果被找到的话，至少得有 10000 个十进位长度（参见 [@mar04]）。

下面我们正式给出 `Baillie-PSW检测`\index{Baillie-PSW检测}。

::: {#def-al:psw .definition}
## 算法：Baillie-PSW检测
1. 使用小素数试除 $N$，若能整除，输出 $N$ 为合数。
2. 使用基为 2 的 Rabin-Miller 强伪素数检测 @def-al:rabin，若 $N$ 非强伪素数，输出 $N$ 为合数。
3. 选择以下两种方法之一确定 Lucas 序列的参数 $P$，$Q$：
   - (Selfridge 建议) 取 $D$ 为 $5,-7,9,-11,13,\ldots$ 中使得 $\legendre{D}{N}=-1$ 的第一个数，选择 $P=1$，$Q=\frac{1-D}{4}$；
   - (Baillie 建议) 取 $D$ 为 $5,9,13,17,21,\ldots$ 中使得 $\legendre{D}{N}=-1$ 的第一个数，选择 $P$ 为 $>\sqrt{D}$ 的最小奇数，$Q=\frac{P^2-D}{4}$。
4. 使用 $P$，$Q$ 为参数的 Lucas 伪素数检测算法 @def-al:lpsp，若 $N$ 非 Lucas 伪素数，输出 $N$ 为合数，否则输出 $N$ 可能为合数。
    用算法 @def-al:sqrtest 检测 $N$ 是否为完全平方数。
:::

::: {.remark}
由于 $D=P^2-4Q^2$，只需尝试模 4 余 1 的数。
Selfridge 建议方法中不使用 $-3$ 是因为当 $D=-3$ 时有 $P=Q=1$，
将会产生以 $\{1,1,0,-1,-1,0\}$ 为循环节的周期 Lucas 序列，
这将使得每个奇合数变成关于 $P,Q$ 的 Lucas 伪素数，并非我们所想要的。
:::

::: {.remark}
若第三步中尝试过程中计算出前若干个 $\legendre{D}{N}$ 均为 1，则 $N$ 很可能为完全平方数，
此时可用算法 @def-al:sqrtest 对 $N$ 进行平方检测以防止额外的计算，若 $N$ 不是平方数则继续寻找 $D$ 的过程。
另外尝试过程中若计算得 $\legendre{D}{N}=0$，则意味着 $N$ 必为合数，可直接终止计算。
:::

::: {.remark}
[@bai80] 证明了，在第三步中，两种方法取到合适的 $D$ 的平均尝试次数小于 $2$。
:::




<!-- 
## 未发表的章节

::: {.callout-warning}
    以下章节在 MUSE 中为注释文本
:::

::: {#def-quadratic-integer}
### 二次域中的整数
设 $z\in \mathbb{Q}(\sqrt{D})$，$p,q\in\mathbb{Z}$，若 $z$ 满足方程 $z^2+pz+q=0$，则称 $z$ 为 $\mathbb{Q}(\sqrt{D})$ 中的整数。
通常意义下的整数（$\in \mathbb{Z}$）则称为有理整数，下同。
:::

通过直接的计算可以得到：

::: {#prp-kd-integer}
### 命题
$\mathbb{Q}(\sqrt{D})$ 中的整数均有以下形式
$$x=\begin{cases}
  r+s\sqrt{D} & \text{若}D\equiv2,3 \pmod{4},\\ \noalign{\smallskip}
  r+s{\displaystyle\frac{-1+\sqrt{D}}{2}}& \text{若}D\equiv1\pmod{4}.
\end{cases}$$
其中 $r$，$s$ 为有理整数，简记为 $r+s\rho$。
:::

::: {.remark}
对于 $D$ 为负数的情形，$\mathbb{Q}(\sqrt{D})$ 中的整数对应于复平面上的某类格点。
:::

::: {#def-kd-conjugate}
### 定义
$\bar{x}=r-s\sqrt{D}$ 称为 $x=r+s\sqrt{D}$ 共轭。
有理整数 $x\bar{x}$ 称为 $x$ 的模，记为 $N(x)$。
:::

::: {#def-quadratic-unit}
### 定义
若 $N(x)=\pm1$，则称 $x$ 为 $\mathbb{Q}(\sqrt{D})$ 中的单位。
:::

::: {#def-associated}
### 定义
两个整数称为相伴的（associated），如果其商为单位。
:::

::: {#def-quadratic-divisibility}
### 二次域中的整除性
设 $\alpha$，$\beta$，$\gamma$ 为整数，如果有 $\alpha=\beta\gamma$，则称 $\beta\mid\alpha$，$\gamma\mid\alpha$
（此时必有 $N(\beta)\mid N(\alpha)$，$N(\gamma)\mid N(\alpha)$）。
:::

类似可以引入 $\mathbb{Q}(\sqrt{D})$ 中的关于有理整数的同余关系、最大公因子等等。
设 $n$ 为有理整数，则有
$$r+s\rho\equiv0\pmod{n}\Leftrightarrow r\equiv s \equiv0 \pmod{n}.$$

下面我们给出十分重要的 Fermat 小定理与 Euler 定理在二次域中的类似形式。

::: {#thm-kd-fermat}
### 二次域中的 Fermat 小定理
设 $a\in \mathbb{Q}(\sqrt{D})$ 为整数，$p$ 为奇有理素数，则有
$$a^p\equiv\begin{cases}
  a&\text{若}\displaystyle\legendre{D}{p}=1\\\noalign{\smallskip}
  \bar{a}&\text{若}\displaystyle\legendre{D}{p}=-1
\end{cases}\pmod{p}
$$ {#eq-kd-fermat}
:::

::: {.proof}
用 $a$ 的表示进行二项展开，利用 Fermat 小定理以及二次剩余的 Euler 准则。
:::

::: {.remark}
由上述定理立即得到，当 $\legendre{D}{p}=-1$ 时，有 $a^{p+1}\equiv N(a)\pmod{p}$。
:::

::: {#thm-kd-euler}
### 二次域中的 Euler 定理
设 $(a,p)=1$，若 $\legendre{D}{p}=1$，则
$$a^{p^{n-1}(p-1)}\equiv1\pmod{p^n}.$$
若 $\legendre{D}{p}=-1$，则
$$a^{p^{n-1}(p+1)}\equiv(N(a))^{p^{n-1}}\pmod{p}.$$
:::

::: {.proof}
利用式 @eq-kd-fermat 及二项式展开。
:::

::: {#def-lucas-seq}
### Lucas 序列
设 $P$，$Q$ 为有理整数，特征方程 $\lambda^2-P\lambda+Q=0$ 的两根为 $a$，$b(= \bar{a})$。
对应的 Lucas 序列为
$$U_n=\frac{a^n-b^n}{a-b},\qquad V_n=a^n+b^n.$$
:::

::: {.remark}
由特征方程对应的递推关系，知道 $\{U_n\}$，$\{V_n\}$ 均为有理整数序列。
:::

::: {#lem-lucas-mod}
### 引理
设 $D$ 为 $P^2 - 4Q$ 的非平方部分，$(2QD,p)=1$，$p$ 为有理素数，则
$$U_{p^{n-1}\left(p-\legendre{D}{p}\right)}\equiv0\pmod{p}$$
:::

::: {.proof}
对 $a$ 和 $\bar{a}$ 分别应用定理 @thm-kd-euler ，
再由 $U_{p^{n-1}\left(p-\legendre{D}{p}\right)}$ 的定义即知。
:::

我们给出形式上与 Lehmer 检测十分相近的

::: {#thm-lucas}
### Lucas 检测
设有素因子分解 $N+1=\prod\limits_{j=1}^nq_j^{\beta_j}$，
若有 Lucas 序列 $\{U_n\}$，使 $(2QD,N)=1$，且满足
$$(U_{(N+1)/q_j},N)=1,\qquad \forall j=1,2,\ldots,n$$
且
$$U_{N+1}\equiv0\pmod{N}.$$
则 $N$ 为素数。
:::

::: {.proof}
设 $N=\prod\limits_{i=1}^np_i^{\alpha_i}$，
记 $S_i=p_i^{\alpha_i-1}\left(p_i-\legendre{D}{p_i}\right)$。
由上述引理得到
$$U_{S_i}\equiv0\pmod{p_i^{\alpha_i}}.$$
设 $M=\left\{k\mid U_k\equiv0\pmod{p_i^{\alpha_i}}\right\}$。
则根据 Lucas 序列的定义知 $M$ 有以下性质：
$$k_1,k_2\in M\Rightarrow k_1\pm k_2\in M.$$
令 $d=\mathrm{LCM}\{S_1,\ldots,S_n\}$，即 $S_1,\ldots,S_n$ 的最小公倍数。
由 $M$ 的上述性质，完全类似于定理 @thm-fermat-converse 的论证，可知 $d\mid N+1$ 但 $d\nmid\frac{N+1}{q_j}$，
得到 $q_j^{\beta_j}\mid d\Rightarrow N+1\mid d\Rightarrow d=N+1$。

然而另一方面，若 $n=1$，$N=p_1^{\alpha_1}$ 且 $\alpha_1\ge2$ 则
\begin{align*}
  d&=2N\cdot\frac{1}{2}\left(1+\frac{1}{p_j}\right)\\
    &=N\left(1+\frac{1}{p_j}\right)\\
      &\ne N+1;
\end{align*}
若 $n\ge2$，由
\begin{align*}
  d&=2\cdot \mathrm{LCM}\left\{\frac{1}{2}\left(p_i-\legendre{D}{p_i}\right)p_i^{\alpha_i-1}\Bigm| i=1,\ldots,n\right\}\\
  &\le2\prod\limits_{i=1}^n\frac{1}{2}\left(1-\frac{1}{p_i}\legendre{D}{p_i}\right)p_i^{\alpha_i}\\
  &\le2N\prod\limits_{i=1}^n\frac{1}{2}\left(1+\frac{1}{p_i}\right)\\
  &\le2N\frac{1}{2}\left(1+\frac{1}{3}\right)\cdot\frac{1}{2}\left(1+\frac{1}{5}\right)\\
  &=\frac{1}{2}N\left(1+\frac{1}{3}\right)\left(1+\frac{1}{5}\right)\\
  &<N+1.
\end{align*}
从而必有 $n=1$，$\alpha_1=1$，即 $N$ 为素数。
:::

Lucas 检测的一个优势在于，Lucas 序列可以通过递推快速地计算。
设
$$A_k=\begin{bmatrix}
  U_{k+1}&V_{k+1}\\
  U_k & V_k
\end{bmatrix},
$$
则有
$$A_k=\begin{bmatrix}
  P & -Q\\
  1 & 0\\
\end{bmatrix}A_{k-1}=\cdots=\begin{bmatrix}
  P & -Q\\
  1 & 0\\
\end{bmatrix}^kA_0.
$$
可以使用快速求幂的方法在 $\log k$ 步中完成序列的计算。

::: {.remark}
上述基于 $N+1$ 分解的算法对 Mersenne 素数 $2^n-1$ 尤其简单，
因此也被著名的 [GIMPS](http://www.mersenne.org/)（Great Internet Mersenne Prime Search）所采用。
目前为止已知的最大的 Mersenne 素数是 GIMPS 计划在 2008 年 8 月 23 日找到的第 45 个 Mersenne 素数，共有 12978189 个十进制位。
有趣的是，2008 年 9 月 6 日找到的第 46 个 Mersenne 素数要比第 45 个来的小。
:::

::: {#thm-lucas-mersenne}
### 对 Mersenne 素数的 Lucas-Lehmer 检测
设 $n$ 为奇数，$v_0=4$，$v_k=v_{k-1}^2-2$。
则 $M_n=2^n-1$ 为素数当且仅当
$$v_{n-2}\equiv0\pmod{M_n}.$$
:::

::: {.proof}
证明思想可以完全跟随定理 @thm-lucas ，然而仍有一些技术上的区别，这里就不赘述了。
完整的可见 Lehmer 在 1930 的证明 @lehmer1930 。
另外 J.W.Bruce 在 1993 年给出了一个短至 2 页"trival"版证明 @bruce 。
:::

与 $N-1$ 型检测完全类似的得到以下结果。

::: {#thm-relaxed-lucas}
### Lucas 检测的放宽版本
设 $N+1=RF$，$(R,F)=1$ 且 $R<F$，有素因子分解 $F=\prod\limits_{j=1}^n q_j^{\beta_j}$。
若有 $\{U_k\}$ 为 Lucas 序列，$(2QD,N)=1$，满足
$$(U_{(N+1)/q_j},N)=1,\qquad \forall j=1,\ldots,n$$
且
$$U_{N+1}\equiv0\pmod{N}.$$
则 $N$ 为素数。
:::

::: {#def-pseudo-lucas}
### Lucas 伪素数
如果 $N$ 为奇合数，$\{U_k\}$ 为一个 Lucas 序列，$N\nmid Q$，满足 $\legendre{D}{N}=-1$ 且 $U_{N+1}\equiv0\pmod{N}$，
则称 $N$ 为（关于 $P$，$Q$）的 Lucas 伪素数。
:::
-->
